rust-lang/edition-guide

- src/editions/transitioning.md
> Document how to transition between editions

- src/2018/index.md
- src/2018/transitioning/traits/impl-trait.md
The first is just removing the double use of "create". The second is opening the `impl Trait` section by saying what it is, not where it can appear.
> Minor edits

- src/editions/index.md
I was a little confused why adding a keyword breaks backwards compatibility. I thought maybe forwards compatibility was meant instead, until I realised how it can break backwards compatibility.
This PR is a proposition for adding an explanation.
WDYT?
> Explain how adding keywords break compat

- src/2018/transitioning/ownership-and-lifetimes/anonymous-lifetime.md
- src/2018/transitioning/ownership-and-lifetimes/default-match-bindings.md
- src/2018/transitioning/ownership-and-lifetimes/in-band-lifetimes.md
- src/2018/transitioning/ownership-and-lifetimes/lifetime-elision-in-impl.md
- src/2018/transitioning/ownership-and-lifetimes/struct-inference.md
A few changes here:
- Rewrote the in-band lifetime section, which was incorrect (seemed to be based on the initial RFC rather than what was actually merged/implemented)
- Removed references to particular compiler versions. I intend to send a separate PR introducing a table of all the 2018 features, their stabilization status, and links to tracking issues where appropriate.
- Assorted minor tweaks/consistency issues.
I didn't touch slice patterns yet, because I think it should be moved to a separate section (it's not particularly connected to ownership or lifetimes).
> Lifetime section edits

- src/2018/transitioning/ownership-and-lifetimes/default-match-bindings.md
* Fix type error in example (it forgot to borrow the option)
* Use a String instead of `&str` so that `ref` is required.
* Avoid implying that `move` patterns exist.
* default binding modes apply to more than just `match`
Closes #30
> several changes to match-default-bindings.md

- src/editions/index.md
This will help people to better understand the place of Rust 2015 as Rust 2018 comes out, and similar for any other edition as each new edition lands.
> Suggested clarifications

- src/2018/status.md
Also change it to "Unstable; tracking issue" since it has been implemented behind a feature gate.
> Add link to tracking issue for "T: 'a inference in structs"

- src/editions/index.md
- src/editions/transitioning.md
* Reflect that `rustfix` is now just `cargo fix` and distributed directly with
Cargo.
* Update that enabling the 2018 edition doesn't enable any warnings, but mention
the `rust_2018_idioms` lint which does indeed enable warnings.
* Tweak some wording here and there with recent tweaks to the workflow
> Tweak and update the transition guide

- src/editions/index.md
The old text ("The Rust compiler can link crates of any editions together") made it sound like old compilers would somehow magically be able to support language features from newer editions.  
The goal of this new text is to make it more clear that a given compiler release will only be able to work with the specific editions that it supports.
> Small clarification to edition compatibility

- src/2018/status.md
This change falls out of some of the discussion in #63.  I don't feel particularly strongly about this change, but I do think it helps provide some useful context for this table.
> Added note about 2015 features in the feature status table

- src/editions/transitioning.md
Related to https://github.com/rust-lang/cargo/issues/5778.
Based on feedback from the [internals thread](https://internals.rust-lang.org/t/help-test-out-the-2018-module-system-changes/8047/20?u=johnthagen), hopefully this clarification will help people realize not to pass the `--prepare-for` flag after they've already transitioned to the new edition.
Hopefully removes a paper cut when others test out this feature.
> Explicitly mention not passing prepare flag after switching to new edition

- src/2018/status.md
I think 3666108ecd7ecc4bee1f2b2240e9f447044b60bb broke the 2018 status links. For example: `impl Trait` on https://rust-lang-nursery.github.io/edition-guide/2018/status.html links to `https://rust-lang-nursery.github.io/edition-guide/2018/2018/transitioning/traits/impl-trait.html` (notice the `2018/2018`).
Note that I changed this in the GitHub editor and did not test it.
> Fix 2018 status links

- src/editions/transitioning.md
This'll be a new flag being added to Cargo to help transitioning to the idioms
of the 2018 edition.
At the same time this removes the `+nightly` invocations from Cargo commands,
removes `--all-targets` as it's the default, and finally removes
`--all-features` as the default of `--all-targets` should be enough.
> Migrate to using `cargo fix --edition-idioms`

- src/2018/status.md
- src/2018/transitioning/concurrency/async-await.md
- src/2018/transitioning/concurrency/index.md
- src/editions/transitioning.md
This PR should fix #29.
It does not remove the concurrency chapter (https://rust-lang-nursery.github.io/edition-guide/2018/transitioning/concurrency/index.html) but does update things to reflect reality and notes that async / await won't ship with the release of Rust 2018.
Maybe we should remove that chapter as well...?
> fix #29 (async await listed as both available and not available).

- src/rust-2018/path-clarity.md
For the final Rust 2018 release, we can delete the section that doesn't
apply, and change the various qualified references like "the uniform
paths variant of Rust 2018" to just "Rust 2018".
> path-clarity: Document new uniform paths variant

- src/rust-2018/data-types/union-for-an-unsafe-form-of-enum.md
[/src/rust-2018/data-types/union-for-an-unsafe-form-of-enum.md](https://github.com/rust-lang-nursery/edition-guide/blob/7c18f376e9de562c28f46c02f3afe3b4941ff6c2/src/rust-2018/data-types/union-for-an-unsafe-form-of-enum.md)
> ..., that means reading or writing a union’s field is unsafe:
```rust
let mut u = MyUnion { f1: 1 };
unsafe { u.f1 = 5 };
let value = unsafe { u.f1 };
```
Writing to a union field is actually safe. The above code snippet produces a compiler warning.
```
warning: unnecessary `unsafe` block
--> src/main.rs:9:5
|
9 |     unsafe { u.f1 = 5 };
|     ^^^^^^ unnecessary `unsafe` block
|
= note: #[warn(unused_unsafe)] on by default
```
This pull request removes the `unsafe` block from the snippet as well as tweaking the text.
* * *
Note:
```
$ rustc -V
rustc 1.28.0 (9634041f0 …
```
> It is safe to write to a union field

- src/SUMMARY.md
- src/rust-2018/trait-system/no-anon-params.md
cc https://github.com/rust-lang/rust/issues/41686
cc @Centril
> Document deprecation of anon params

- src/rust-2018/macros/macro-changes.md
> macro_rules -> macro_use

- src/rust-2018/module-system/path-clarity.md
In Rust 2015, if you have a submodule:
```rust,ignore
///  foo.rs 
///  or 
///  foo/mod.rs
mod foo;
```
It can live in `foo.rs` or `foo/mod.rs`. If it has submodules of its own, it
*must* be `foo/mod.rs`. So a `bar` submodule of `foo` would live at
`foo/bar.rs`.
In Rust 2018, `mod.rs` is no longer needed. 
```rust,ignore
///  foo.rs 
///  foo/bar.rs
mod foo;
/// in foo.rs
mod bar;
```
`foo.rs` can just be `foo.rs`,
and the submodule is still `foo/bar.rs`. This eliminates the special
name, and if you have a bunch of files open in your editor, you can clearly
see their names, instead of having a bunch of tabs named `mod.rs`.
> Clearer documentation for "No more mod.rs"

- src/rust-2018/ownership-and-lifetimes/lifetime-elision-in-impl.md
Now that https://github.com/rust-lang/rust/pull/54778 is in.
(I don't know when this should be committed, but I figured I'd post the PR regardless.)
> Mark impl-header-lifetime-elision as 1.31 instead of beta

- src/rust-2018/module-system/path-clarity.md
Most of the page but the last section describes anchored paths.
The original example works for uniform paths which are described only at the bottom of the page as a possible alternative to anchored paths -- https://github.com/rust-lang/rust/issues/53130#issuecomment-418824862 indicates that anchored paths may be chosen, at least for now, while leaving the door open for uniform paths.
> Fix extern crate alias example for anchored paths

- src/editions/transitioning-an-existing-project-to-a-new-edition.md
This updates the idiom migration section to indicate that
`--broken-code` is a flag that can be used to make more progress when
fixing code with the idiom lints, and it also more strongly indicates
that idiom lints are not ready for prime time and bugs are to be
expected.
Closes rust-lang/rust#55955
> Update documentation for `cargo fix --broken-code`

- src/rust-2018/error-handling-and-panics/aborting-on-panic.md
When trying to use the provided config, cargo warns:
```
warning: unused manifest key: profile.debug
warning: use `[profile.dev]` to configure debug builds
```
> aborting-on-panic.md: Typo in example config

- src/SUMMARY.md
- src/rust-2018/edition-changes.md
> Add 2018-specific changes.

- src/rust-2018/macros/at-most-once.md
The [release notes for 1.32.0](https://github.com/rust-lang/rust/blob/stable/RELEASES.md#version-1320-2019-01-17) confirm that the `?` Kleene operator was only just added in `1.32.0`, and was not supposed to be part of `1.31.0` ("Rust 2018"). This adds a minimum Rust version badge to that section.
Closes #128.
> Add minimum Rust version for Kleene operator

- src/rust-2018/ownership-and-lifetimes/the-anonymous-lifetime.md
I think this is what was stabilized in 1.31.  It's not really clear to me what is left to be done (why the tracing issue is still open).  There's also `impl_header_lifetime_elision` which I [can't quite figure out](https://github.com/rust-lang-nursery/reference/issues/479).
> Update for anonymous-lifetime stabilization.

- src/rust-2018/edition-changes.md
- src/rust-2018/module-system/path-clarity.md
This is just a rough stab at improving things, or at least removing some of the wrong information.  I think more details will need to wait for the reference.
I rewrote `Changes to paths` because it no longer matched what current 2018 code should look like, and had a lot of overlap with what "uniform paths" was saying.  I replaced it with something roughly describing extern prelude, which I think fits?
Closes #139.
> Update for uniform_path stabilization.

- src/rust-2018/edition-changes.md
See https://github.com/rust-lang/rust/pull/55632.
> overflowing_literals is deny on all editions

- src/rust-2018/data-types/inclusive-ranges.md
The default for mdbook is 2015, so this was testing old behavior.
Now that overflowing_literals is deny-by-default on all editions,
the test was failing. This updates for the new behavior.
> Fix test now that overflowing_literals is rejected in all editions.

- src/rust-2018/edition-changes.md
The linkchecker in the rust repo rejects this because there are duplicate
HTML id's. The theme selector uses the id "rust" for the Rust color theme.
See https://github.com/rust-lang-nursery/mdBook/issues/880 for more info.
This blocks updating upstream.
> Fix issue with rust's linkchecker and mdbook.

- README.md
- src/editions/transitioning-an-existing-project-to-a-new-edition.md
- src/rust-2018/cargo-and-crates-io/index.md
- src/rust-2018/control-flow/index.md
- src/rust-2018/data-types/index.md
- src/rust-2018/documentation/index.md
- src/rust-2018/edition-changes.md
- src/rust-2018/error-handling-and-panics/index.md
- src/rust-2018/macros/index.md
- src/rust-2018/module-system/index.md
- src/rust-2018/module-system/path-clarity.md
- src/rust-2018/ownership-and-lifetimes/index.md
- src/rust-2018/ownership-and-lifetimes/lifetime-elision-in-impl.md
- src/rust-2018/platform-and-target-support/index.md
- src/rust-2018/rustdoc/index.md
- src/rust-2018/the-compiler/index.md
- src/rust-2018/trait-system/dyn-trait-for-trait-objects.md
- src/rust-2018/trait-system/index.md
Now that rust-lang/rust supports mdbook 0.2, migrate to it.
This is the result of running the script
https://gist.github.com/ehuss/b2a647eb69aa8f57bc4fb397656dfac1
I have tested in-repo with linkchecker, and it seems to be ok. I can handle
updating the submodule once this is merged.
> Migrate to mdbook 0.2.

- README.md
Updating links to point to the docroot of the html book and including notes in README.md about using a webserver to view the output.
This addresses #126
> Links fixes

- src/rust-2018/rustup-for-managing-rust-versions.md
not needed 'toolchain' in changing default toolchain for rustup command.
> fix command

- src/rust-2018/edition-changes.md
- src/rust-2018/ownership-and-lifetimes/non-lexical-lifetimes.md
Enabled in https://github.com/rust-lang/rust/pull/59114
> Update now that NLL is enabled in 2015.

- src/rust-2018/documentation/new-editions-of-the-book.md
- src/rust-2018/trait-system/more-container-types-support-trait-objects.md
Now that there is one book to rule them all, some of the links needed updating.
The prose needed significant adjustment to accommodate the most recent changes.
I did my best to capture what is going on, but I am not confident it is correct.
> Fix links for book editions.

- src/rust-2018/error-handling-and-panics/controlling-panics-with-std-panic.md
I copied the example and was hit with a compiler warning.
> Fix typo in controlling-panics-with-std-panic.md

- src/rust-2018/macros/at-most-once.md
Fixes https://github.com/rust-lang-nursery/edition-guide/issues/161
r? @ehuss
> Part 2: Rust 2015 now supports ? macro rep op

- src/editions/transitioning-an-existing-project-to-a-new-edition.md
- src/rust-2018/cargo-and-crates-io/cargo-check-for-faster-checking.md
- src/rust-2018/cargo-and-crates-io/cargo-new-defaults-to-a-binary-project.md
- src/rust-2018/cargo-and-crates-io/cargo-rustc-for-passing-arbitrary-flags-to-rustc.md
- src/rust-2018/cargo-and-crates-io/index.md
- src/rust-2018/control-flow/loops-can-break-with-a-value.md
- src/rust-2018/data-types/inclusive-ranges.md
- src/rust-2018/module-system/path-clarity.md
- src/rust-2018/the-compiler/incremental-compilation-for-faster-compiles.md
- src/rust-2018/trait-system/dyn-trait-for-trait-objects.md
- src/rust-2018/trait-system/impl-trait-for-returning-complex-types-with-ease.md
- src/rust-2018/trait-system/more-container-types-support-trait-objects.md
I recently had a reason to read through the entire edition guide, if you couldn't tell from all the tracking issues I opened 😛 
I have a few small fixes for things I noticed along the way that I rolled into this one PR; I'm happy to split these out into separate PRs (either one PR per commit or certain commits in separate PRs if some changes need more discussion).
I tried to stay to relatively uncontroversial fixes, I wouldn't say this is a thorough copy-edit or anything.
> Small fixes

- README.md
PR fixes the broken Travis build badge.  (See https://github.com/dmitris/edition-guide/tree/patch-1 for the working badge).
> correct the travis build badge URL

- src/rust-2018/the-compiler/improved-error-messages.md
NLL makes the example not an error anymore, but a small tweak makes it fail again.
Fixes #159.
> Fix error example for modern compilers.

- src/rust-2018/cargo-and-crates-io/cargo-install-for-easy-installation-of-tools.md
Since a new thought is introduced here. It is better to separate it by a corresponding title.
> #184 More clear explanation and Title.

- src/rust-2018/rustup-for-managing-rust-versions.md
> Remove -preview for rustup components.

- src/rust-2018/module-system/path-clarity.md
The example code was a little confusing. Instead, use a table which compares
the directory structure.
Not sure if this is clear enough, it's a little awkward to explain.
[Rendered](https://github.com/ehuss/edition-guide/blob/fb53ec9b6915760013865e62772f3404b3563e08/src/rust-2018/module-system/path-clarity.md#no-more-modrs)
> Attempt to clarify "no more mod.rs".

- src/rust-2018/ownership-and-lifetimes/the-anonymous-lifetime.md
> Hide extraneous `use` in anonymous lifetime example.

- src/rust-2018/rustup-for-managing-rust-versions.md
rust-lang/rustup#2148
Signed-off-by: zakaluka <zakthrow@gmail.com>
> Updated install and uninstall instructions

- src/rust-2018/platform-and-target-support/musl-support-for-fully-static-binaries.md
> Fix forge link.

- src/SUMMARY.md
- src/rust-next/no-more-fnbox.md
> Add contents for Rust 1.35

- src/SUMMARY.md
- src/rust-next/alloc.md
- src/rust-next/cargo-vendor.md
- src/rust-next/future.md
- src/rust-next/maybe-uninit.md
> update guide for 1.36 and 1.37

- .github/workflows/main.yml
The old method of echoing commands is being deprecated, see https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/.
> Update deprecated GitHub Actions commands.

- src/rust-2018/error-handling-and-panics/question-mark-in-main-and-tests.md
I was trying to figure out why my error messages were not printing how I wanted them to (using Display). This page in the edition book is one of the first links that pops up when I googled it, but it wasn't till I saw [this post on the rust forum](https://users.rust-lang.org/t/how-to-customize-the-main-error-message-when-returning-an-error/21903) that I realized there was no way to do this "automatically", so I thought it might be helpful for others to clarify in these docs as well.
> Clarify the limitation of ? in main and tests

- src/rust-2018/data-types/inclusive-ranges.md
- src/rust-2018/edition-changes.md
- src/rust-2018/module-system/path-clarity.md
- src/rust-2018/rustdoc/documentation-tests-can-now-compile-fail.md
- src/rust-next/const-fn.md
Just a few updates/fixes that I've run across.
> A few small updates.

- src/rust-2018/slice-patterns.md
The previous phrasing was not precise enough, and suggested that the `[first, second]` pattern would match any slice with at least two elements, while in fact it only matches slices with exactly two elements.
> Clarify slice patterns example

- src/rust-2018/platform-and-target-support/musl-support-for-fully-static-binaries.md
musl libc has moved to from https://www.musl-libc.org/ to https://musl.libc.org/
> Update musl libc link

- README.md
- book.toml
This adds a little icon in the upper-right corner so that readers can find the source if they want to make changes or file issues. This is already included in several of the other books.
This also includes some updates to the README for building the book locally.
> Add git link to the source.

- src/rust-2018/module-system/path-clarity.md
There was some reorganization in the reference as part of https://github.com/rust-lang/reference/pull/937.
> Update link for no_std.

- src/rust-2021/warnings-promoted-to-error.md
> Add more info for warnings promoted to errors

- src/rust-2021/disjoint-capture-in-closures.md
- triagebot.toml
This PR adds additional information about disjoint capture in closures such as changes in semantics and migration instructions.
r? @nikomatsakis
Closes https://github.com/rust-lang/edition-guide/issues/241
> Provide more information about disjoint capture in closures and migration instructions

- src/rust-2021/prelude.md
- triagebot.toml
([rendered](https://github.com/rylev/edition-guide/blob/prelude/src/rust-2021/prelude.md))
Supersedes #248. Fixes #235.
> Add Rust 2021 prelude migration details

- src/rust-2021/IntoIterator-for-arrays.md
> Add migration section to into-iterator

- src/rust-2021/or-patterns-macro-rules.md
> Add migration details to or-patterns guide

- src/rust-2021/default-cargo-resolver.md
> Add details on migrating the Cargo feature resolver.

- src/SUMMARY.md
- src/editions/advanced-migrations.md
- src/editions/transitioning-an-existing-project-to-a-new-edition.md
This updates the transitioning chapter to make it more up-to-date, and to correct some issues.
I decided to leave it with a 2018 example, since I think it is clear enough. Most of the 2021 lints are pretty obscure or complicated, and I think readers will get the gist of what it is saying.  I also feel like rewriting this for every edition will be a bit tedious.
This also adds a new chapter to help people if they are having trouble, or need advanced information.
> Update transitioning chapter.

- src/rust-2021/panic-macro-consistency.md
> Add migration section for panic-macro-consistency

- src/rust-2021/reserving-syntax.md
cc https://github.com/rust-lang/edition-guide/issues/242
> reserving-syntax.md: Expand and add detail

- src/rust-2021/disjoint-capture-in-closures.md
- src/rust-2021/or-patterns-macro-rules.md
- src/rust-2021/prelude.md
- src/rust-2021/reserving-syntax.md
- src/rust-2021/warnings-promoted-to-error.md
This addresses #250 though it only does so for Rust 2021.
> Add more consistent headings and add a migration section to reserving-syntax

- src/SUMMARY.md
- src/editions/creating-a-new-project.md
- src/editions/transitioning-an-existing-project-to-a-new-edition.md
- src/rust-2021/index.md
This updates the "under construction" parts of the guide for the stabilization of 2021. This also includes PR #254.
Closes #265
> Update for 2021 stabilization

- src/rust-2021/default-cargo-resolver.md
There was some confusion about how the resolver works in a workspace, so this adds a little clarification.
Closes https://github.com/rust-lang/cargo/issues/9956
> Clarify cargo resolver behavior in a workspace.

- src/rust-2021/prelude.md
It seems that there is a minor syntax error in the code example: a close angle bracket is missing.   I fixed it.
> Fix syntax error in code example

- src/rust-2021/default-cargo-resolver.md
> Add a missing period

- src/rust-2021/disjoint-capture-in-closures.md
- Fix a broken link to the `UnwindSafe` doc of the standard library reference.
- Remove the second link to the `Clone` doc.
> Fix a broken link in the Disjoint Capture in Closure chapter

- src/editions/creating-a-new-project.md
`+nightly` is no longer needed now that 2021 has been stabilized.
Closes #275
> Remove `+nightly` for `cargo new`

- src/editions/index.md
In the "What are Editions?" section, note that Rust 1.0 was released in May 2015, since it answers a likely question in the mind of the reader considering the preceding commentary referencing that time frame. Writing in Q3 2022, noting the date also helps establish the Rust project's credible commitment to the rule of supporting stable features in perpetuity. It is not something that was just thought up recently -- the project has been adhering to it for more than seven years.
> fixes #277: mention rust 1.0 release month and year

- src/editions/creating-a-new-project.md
Also tighten-up existing prose, and use conventional `$` for (non-root) POSIX shell prompt.
> "Creating a new project": add example using 'cargo new --edition YEAR'

- README.md
- book.toml
- src/SUMMARY.md
- src/editions/index.md
- src/introduction.md
Makes consistent the following references to the title:
"The Edition Guide"       (book.toml -- document title)
(src/SUMMARY.md)
(README.md ["License" section text])
"The Rust Edition Guide"  (README.md [heading])
"the Rust Edition Guide"  (src/introduction.md)
"this Edition Migration Guide"  (src/editions/index.md)
> use title "The Rust Edition Guide" everywhere

- src/rust-2018/path-changes.md
Closes #284
Since rust-lang/rust#112086, paths in `use` statements have the same shadowing rules as other paths, at least for the simple cases we're talking about in this guide.
The case of an external crate having the same name as a local module still seems worth mentioning, so I've put it in the "Extern crate paths" section.
> Update Rust 2018 "Path and module system changes" for Rust 1.72

- src/SUMMARY.md
- src/rust-2021/c-string-literals.md
C-string literals have been stabilized as of https://github.com/rust-lang/rust/pull/117472 as part of the 2021 edition.
> Add C-string literals.

- src/rust-2021/c-string-literals.md
The C-string literal stabilization has been delayed one release via https://github.com/rust-lang/rust/pull/119528.
> Update c-string literal stabilization release number.

- src/SUMMARY.md
- src/editions/transitioning-an-existing-project-to-a-new-edition.md
- src/rust-2024/cargo-remove-implicit-features.md
- src/rust-2024/index.md
- src/rust-2024/public-private-dependencies.md
- src/rust-2024/rpit-lifetime-capture.md
- src/rust-2024/rustfmt-overflow-delimited-expr.md
- src/rust-2024/static-mut-reference.md
- src/rust-2024/unsafe-op-in-unsafe-fn.md
This sets up a (mostly empty) outline for what has been accepted for the 2024 edition so far.
Closes #290
> Set up scaffolding for 2024

- src/rust-2024/cargo-remove-implicit-features.md
- src/rust-2024/public-private-dependencies.md
- src/rust-2024/rpit-lifetime-capture.md
- src/rust-2024/rustfmt-overflow-delimited-expr.md
- src/rust-2024/static-mut-reference.md
- src/rust-2024/unsafe-op-in-unsafe-fn.md
This is just a rough start to add at least a little information about the current changes.
> Add some more initial stub docs for 2024.

- src/editions/index.md
This is mostly just a pass over the grammar, wording, and sections featured in the editions index.
It also reduces the manual line breaks - in Markdown, these make following sentences quite difficult. If you'd like them added back, please let me know!
> Clean up the `editions/index.md` page

- src/rust-2024/static-mut-reference.md
A bit more detail behind the reasoning and alternatives.
> Flesh out detail behind disallowing refs to static mut

- src/rust-2024/prelude.md
Following the changes made in https://github.com/rust-lang/rust/pull/116016.
> Document RustcEncodable/RustcDecodable

- src/SUMMARY.md
- src/rust-2024/cargo-inherited-default-features.md
- src/rust-2024/cargo-remove-implicit-features.md
- src/rust-2024/cargo-table-key-names.md
This adds some documentation for some of the cargo changes.
cc https://github.com/rust-lang/rust/issues/123754
cc https://github.com/rust-lang/rust/issues/123750
cc @rust-lang/cargo
> 2024: Document cargo changes

- src/SUMMARY.md
- src/rust-2024/gen-keyword.md
cc https://github.com/rust-lang/rust/issues/123904
> 2024: Document reserving `gen` keyword

- src/SUMMARY.md
- src/rust-2024/unsafe-extern.md
This adds a chapter for unsafe extern blocks for 2024.
> Add 2024 unsafe extern blocks.

- src/SUMMARY.md
- src/rust-2024/unsafe-attributes.md
This adds a chapter for unsafe attributes for 2024.
Draft pending https://github.com/rust-lang/rust/pull/126177.
> Add 2024 unsafe attributes.

- src/SUMMARY.md
- src/rust-2024/never-type-fallback.md
I wrote a draft, it should probably be revised.
cc @traviscross
> Add a section for the never type change in e2024

- src/rust-2024/never-type-fallback.md
Updates for the changes from https://github.com/rust-lang/rust/pull/126881. cc @WaffleLapkin
> 2024: Add note about never_type_fallback_flowing_into_unsafe lint level.

- src/rust-2024/prelude.md
Automatic migration support has been added via https://github.com/rust-lang/rust/pull/125889.
> Add documentation for 2024 prelude migration.

- src/SUMMARY.md
- src/rust-2024/missing-macro-fragment-specifiers.md
This adds a page for the change in https://github.com/rust-lang/rust/pull/128006.
Note that this may become a hard error in all editions. If and when that happens, this PR can be reverted.
> 2024: Add page for missing_fragment_specifier

- src/SUMMARY.md
- src/rust-2024/rpit-lifetime-capture.md
Let's describe the changes to the opaque type lifetime capture rules in some detail.
To do this, we first describe precise capturing, as we'll use that syntax both for describing the meaning of capturing and to describe the migration steps.
Arguably, some of what we describe isn't strictly tied to the edition. People could migrate to the `use<..>` syntax in any edition.  However, this is all part of the same change, both conceptually and practically, so it's better to just describe this in one place.
cc @compiler-errors
Tracking:
- https://github.com/rust-lang/rust/issues/123432
> Add chapter for Lifetime Capture Rules 2024

- src/SUMMARY.md
- src/rust-2024/unsafe-extern.md
This goes after this is merged:
- https://github.com/rust-lang/rust/pull/127921
...and CI is going to be happy after it.
r? @traviscross 
Tracking:
- https://github.com/rust-lang/rust/issues/123743
> Stabilize unsafe extern blocks

- src/rust-2024/newly-unsafe-functions.md
I was a little too fast clicking the merge button in #304, and missed a broken link.
> Fix deprecated_safe_2024 link

- src/rust-2024/macro-fragment-specifiers.md
Adds the chapter for https://github.com/rust-lang/rust/issues/123742.
Draft pending https://github.com/rust-lang/rust/pull/126697 and https://github.com/rust-lang/rust/pull/125627 (next nightly).
> 2024: Add macro-fragment-specifiers.

- src/rust-2024/unsafe-attributes.md
See https://github.com/rust-lang/rust/pull/128771
> Update for unsafe attributes stabilization

- src/SUMMARY.md
- src/rust-2024/rustdoc-doctests.md
Tracking issue: https://github.com/rust-lang/rust/issues/124853
> 2024: Add rustdoc combined doctests

- src/rust-2024/static-mut-references.md
This updates the static_mut_refs chapter for the changes from https://github.com/rust-lang/rust/pull/124895.
> Update static_mut_refs now that it is a lint

- src/rust-2024/rustdoc-doctests.md
The `standalone` tag was renamed to `standalone_crate` in https://github.com/rust-lang/rust/pull/130931.
> Rename doctest standalone tag

- src/rust-2024/rustdoc-doctests.md
This just adds some tips for common scenarios detected during the crater run for rustdoc-doctests to hopefully help people understand any errors they may encounter when updating to the 2024 edition.
> Add some tips for what to be careful of with rustdoc-doctests

- src/SUMMARY.md
- src/rust-2024/rustfmt-raw-identifier-sorting.md
- src/rust-2024/rustfmt-raw-identifiers.md
[rendered](https://github.com/rust-lang/edition-guide/blob/0cbff13a2c44713ca9b7c168d75a225896668cbb/src/rust-2024/rustfmt-raw-identifiers.md)
> add rustfmt raw identifer sorting doc

- src/SUMMARY.md
- src/rust-2024/rustfmt-style-edition.md
https://github.com/rust-lang/rust/issues/123799
[rendered](https://github.com/rust-lang/edition-guide/blob/315514dadac18ef956895359e394d84441df2257/src/rust-2024/rustfmt-style-edition.md)
> 2024: rustfmt style edition

- src/SUMMARY.md
- src/rust-2021/raw-lifetimes.md
- src/rust-2021/reserved-syntax.md
This adds a section for raw lifetimes (and reserved raw lifetimes) added in https://github.com/rust-lang/rust/pull/126452.
cc @compiler-errors
> 2021: Update for raw lifetimes

- src/rust-2024/cargo-resolver.md
Fixed the link to display correctly, as the redundant `/` was causing a Not Found error.
> Fix broken Cargo Book link in cargo-resolver.md

- triagebot.toml
This adds merge conflict notifications added in https://github.com/rust-lang/triagebot/pull/1856
> Enable triagebot merge-conflicts and shortcuts

- src/rust-2024/temporary-if-let-scope.md
In https://github.com/rust-lang/edition-guide/commit/bf89d94e1fa73aca29eaa28c59198ba8f6027c84 I accidentally copied the text from `tail_expr_drop_order` into the `if_let_rescope` chapter, which says that the lint does not automatically apply.
This also adds a note about what to do after the migration.
> Fix `if_let_rescope` applicability

- src/SUMMARY.md
- src/rust-2024/rustfmt-assignment-operator-rhs-indentation.md
Tracking:
- https://github.com/rust-lang/rust/issues/132380
> 2024: Assignment operator RHS indentation

- triagebot.toml
This adds more labeling support from triagebot:
- Allow users to set labels.
- Automatically label new PRs as S-waiting-on-review.
- Automatically flip labels when reviews are requested or submitted.
> Add more triagebot labeling support

- src/SUMMARY.md
- src/rust-2024/match-ergonomics.md
We're reserving some syntax in patterns in Rust 2024.  Let's add a chapter to describe that.
cc @ehuss @nadrieril @jules-bertholet
Tracking:
- https://github.com/rust-lang/rust/issues/131414
> Add chapter for 2024 match ergonomics reservations

- src/editions/transitioning-an-existing-project-to-a-new-edition.md
This updates the transitioning steps with a few additions and clarifications:
1. Recommend running `cargo update` before getting started. Some dependencies may need to be updated to be compatible with the new edition.
2. Clarify the testing step, and highlight that there may be some more manual work needed at this stage.
3. Recommend running `rustfmt` now that formatting changes are tied to editions.
> Update the transitioning steps

- src/SUMMARY.md
- src/rust-2024/rustfmt-formatting-fixes.md
This is an attempt to document the fixes in the 2024 edition of rustfmt.
I'm not sure this is really the best way to present this. I'm not sure how comprehensible this is.
These are taken from https://github.com/rust-lang/rustfmt/issues/5577. I did not re-review to see if there is anything missing. I probably am missing some things here.
Some of these were a little difficult to explain, since I didn't really understand them. Generally I left the description vague since I didn't think being precise was all that important.
Also, sometimes the code had changed several times since the original introduce of the version two check, and the original examples no longer had the same behavior. All of these examples here were generated with the latest nightly.
> 2024: Document rustfmt fixes

- src/rust-2024/rustfmt-overflow-delimited-expr.md
This adds the documentation for `overflow_delimited_expr`.
Tracking issue: https://github.com/rust-lang/rust/issues/123751
Style issue: https://github.com/rust-lang/style-team/issues/149
Style update: https://github.com/rust-lang/rust/pull/114764
Implementation: https://github.com/rust-lang/rustfmt/pull/6260
> 2024: Document rustfmt overflow_delimited_expr

- src/rust-2024/static-mut-references.md
This is an attempt to provide more specific examples on how people can safely work around `static-mut-refs`.
Closes https://github.com/rust-lang/rust/issues/123059
> Add alternatives for static-mut-refs

- src/rust-2024/prelude.md
Needed to fix CI in https://github.com/rust-lang/rust/pull/134272 (FCP still pending in that PR)
> Rustc{En,De}codable has been removed

- src/rust-2024/static-mut-references.md
Thanks for all the work that goes into the guide!
I was reading through the beta version of the guide at https://doc.rust-lang.org/beta/edition-guide/rust-2024/static-mut-references.html#atomics and found this spelling error:
The word "Change" in the first example in the atomics section is spelled "Chnage", this PR fixes that very minor thing.
> Correct spelling error in `static-mut-references.md`

- src/rust-2024/rustfmt-style-edition.md
I don't know if one or the other is really preferred, but I figure the reader can decide for themselves.
Closes https://github.com/rust-lang/edition-guide/issues/371
> Mention both `rustfmt.toml` and `.rustfmt.toml`

- src/rust-2024/cargo-inherited-default-features.md
- src/rust-2024/cargo-resolver.md
- src/rust-2024/cargo-table-key-names.md
- src/rust-2024/newly-unsafe-functions.md
- src/rust-2024/rpit-lifetime-capture.md
- src/rust-2024/temporary-tail-expr-scope.md
This PR will fix some grammar errors found in the book
> fix grammar errors

- src/SUMMARY.md
- src/rust-2024/let-chains.md
Document if and while let chains, to be stabilized in https://github.com/rust-lang/rust/pull/132833 .
cc tracking issue: https://github.com/rust-lang/rust/issues/53667
> Document if/while let chains

- src/rust-2024/missing-macro-fragment-specifiers.md
This lint is planned to be removed in [1], but CI is failing due to linkcheck issues in the edition guide. Remove links and add a note that the lint has become an error in all editions.
[1]: https://github.com/rust-lang/rust/pull/128425
> Update references to the `missing_fragment_specifier` lint

- src/rust-2024/never-type-fallback.md
required for https://github.com/rust-lang/rust/pull/146167#issue-3380589689
> link to never type fallback lint as deny by default
