- src/editions/index.md
As I was reading through, I made a few edits that I thought would help it flow better.
> Make readability edits

- src/2018/transitioning/raw-identifiers.md
Cleanup wording. Should be pretty straightforward.
> Update text in raw-identifiers.md

- src/2018/transitioning/errors/question-mark.md
- src/2018/transitioning/ownership-and-lifetimes/anonymous-lifetime.md
- src/2018/transitioning/ownership-and-lifetimes/default-match-bindings.md
Fixes #16
Suggested review by @Centril. WDYT?
> Add some version references to shipped features

- src/2018/transitioning/errors/question-mark.md
Just a few minor consistency tweaks.
> Error handling edits

- src/editions/index.md
This PR refactors the intro text, mostly to change emphasis by talking about bottom-line impact first.
> Revise Edition introduction

- src/2018/transitioning/modules/macros.md
- src/2018/transitioning/modules/path-clarity.md
Some clarifications and consistency edits.
> Module system revisions

- .travis.yml
(checking to see that CI passes...)
> Temporarily pin guide to 2018-06-20 nightly

- src/2018/transitioning/traits/impl-trait.md
> impl-trait: consistently use old then new style

- src/2018/transitioning/ownership-and-lifetimes/lifetime-elision-in-impl.md
> Split line to avoid scrollbar in guide

- .travis.yml
Hopefully this works.
**Do not merge unless CI passes!**
> Unpin the nightly version from 2018-06-20

- src/2018/status.md
+ Housekeeping
+ Adds the minimum edition to each lang tables in the feature status page.
> add Minimum Edition to Feature Status items in Lang table

- src/2018/transitioning/ownership-and-lifetimes/struct-inference.md
I had to reread the original sentence multiple times to understand its meaning. I think this is clearer.
> Remove double negative and repeated word

- src/2018/transitioning/modules/macros.md
> Document how to transition imports of procedural macros

- src/rust-2018/module-system/raw-identifiers.md
- src/unstable-feature-status.md
Depends on https://github.com/rust-lang/rust/pull/53236.
> Updated status of `raw_identifiers` feature

- src/rust-2018/ownership-and-lifetimes/non-lexical-lifetimes.md
Just a few small error corrections and grammar improvements. :)
> fix spelling on lexical lifetimes page

- src/rust-2018/platform-and-target-support/cdylib-crates-for-c-interoperability.md
> insde -> inside

- src/rust-2018/macros/custom-derive.md
Broken links hunt! :bow_and_arrow:
> Fixes outdated link

- src/rust-2018/edition-changes.md
cc https://github.com/rust-lang-nursery/edition-guide/issues/161
r? @ehuss
> Part 1: Rust 2015 now supports ? macro rep op

- src/rust-2018/edition-changes.md
r? @carols10cents 
Fixes https://github.com/rust-lang-nursery/edition-guide/issues/166.
> Cleanup unused NLL link

- .travis.yml
I would like to beta test a new unstable feature in cargo to handle upgrades for mdbook.
> Try cargo install-upgrade for mdbook.

- src/rust-2018/macros/at-most-once.md
> Fix syntax highlighting in macro guide

- .github/workflows/main.yml
- .travis.yml
Based on https://github.com/rust-lang/reference/pull/705; thanks @ehuss!
> Port from Travis to GitHub Actions

- .github/workflows/main.yml
This can help ensure submodule updates go smoothly.
> Use rust-lang/rust linkchecker on CI.

- src/SUMMARY.md
- src/rust-next/const-fn.md
- src/rust-next/pin.md
> Add stuff for Rust 1.33

- src/rust-2021/or-patterns-macro-rules.md
> Fix typo in or-patterns section

- src/editions/transitioning-an-existing-project-to-a-new-edition.md
"file a bug" --> "file a bug report"
> Fix grammar

- .github/workflows/main.yml
This switches PRs to use merge queues to help ensure that master is evergreen.
> CI: Switch to merge queue

- src/rust-2024/rpit-lifetime-capture.md
This removes the precise capturing features which are no longer needed, and have been removed in https://github.com/rust-lang/rust/pull/136787 which is causing test failures.
> Remove precise capturing features
